//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsText() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExHentaiDownloaderZ_5.Content.Locales.SettingsText", typeof(SettingsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение при изменении списка загрузок.
        /// </summary>
        public static string addElementAutosaveFlag {
            get {
                return ResourceManager.GetString("addElementAutosaveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание бекапов файла автосохранения.
        /// </summary>
        public static string autosaveBackupFlag {
            get {
                return ResourceManager.GetString("autosaveBackupFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс параметров.
        /// </summary>
        public static string cancelSettingsButton {
            get {
                return ResourceManager.GetString("cancelSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение перед проверкой статусов.
        /// </summary>
        public static string checkStatusesAutosaveFlag {
            get {
                return ResourceManager.GetString("checkStatusesAutosaveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка в номерные дочерние папки.
        /// </summary>
        public static string createChildFolderFlag {
            get {
                return ResourceManager.GetString("createChildFolderFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string customTopBarHeader {
            get {
                return ResourceManager.GetString("customTopBarHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержка между загрузкой страниц разных манг:.
        /// </summary>
        public static string downloadMangaDelayLabel {
            get {
                return ResourceManager.GetString("downloadMangaDelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержка между загрузкой страниц манги:.
        /// </summary>
        public static string downloadMangaPageDelayLabel {
            get {
                return ResourceManager.GetString("downloadMangaPageDelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь загрузки:.
        /// </summary>
        public static string downloadPathLabel {
            get {
                return ResourceManager.GetString("downloadPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры загрузки.
        /// </summary>
        public static string downloadSettingsGroupBox {
            get {
                return ResourceManager.GetString("downloadSettingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры подключения к exhentai.
        /// </summary>
        public static string exhentaiSettingsGroupBox {
            get {
                return ResourceManager.GetString("exhentaiSettingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение при выходе из программы.
        /// </summary>
        public static string exitAutosaveFlag {
            get {
                return ResourceManager.GetString("exitAutosaveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранять оригинальное имя файла из галереи.
        /// </summary>
        public static string keepOriginalFileNameCheckBox {
            get {
                return ResourceManager.GetString("keepOriginalFileNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение перед загрузкой информации о манге.
        /// </summary>
        public static string loadInfoAutosaveFlag {
            get {
                return ResourceManager.GetString("loadInfoAutosaveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автосохранение перед загрузкой страниц.
        /// </summary>
        public static string loadPagesAutosaveFlag {
            get {
                return ResourceManager.GetString("loadPagesAutosaveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержка между загрузкой информации о разных мангах:.
        /// </summary>
        public static string mangaInfoLoadDelayLabel {
            get {
                return ResourceManager.GetString("mangaInfoLoadDelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение &quot;ipb_member_id&quot; из куков:.
        /// </summary>
        public static string memberIdLabel {
            get {
                return ResourceManager.GetString("memberIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос нового пути загрузки при запуске (если убрать флаг всегда будет новый путь загрузки).
        /// </summary>
        public static string newFolderRequestFlag {
            get {
                return ResourceManager.GetString("newFolderRequestFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие папки загрузки после завершения.
        /// </summary>
        public static string openDownloadFolderFlag {
            get {
                return ResourceManager.GetString("openDownloadFolderFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение &quot;ipb_pass_hash&quot; из куков:.
        /// </summary>
        public static string passHashLabel {
            get {
                return ResourceManager.GetString("passHashLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержка между подгрузками списков страниц:.
        /// </summary>
        public static string rootPageLoadDelayLabel {
            get {
                return ResourceManager.GetString("rootPageLoadDelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string saveSettingsButton {
            get {
                return ResourceManager.GetString("saveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры сохранения.
        /// </summary>
        public static string saveSettingsGroupBox {
            get {
                return ResourceManager.GetString("saveSettingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прокрутка до активной строки.
        /// </summary>
        public static string scrollToActiveCheckBox {
            get {
                return ResourceManager.GetString("scrollToActiveCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прокрутка до добавленной строки.
        /// </summary>
        public static string scrollToAddCheckBox {
            get {
                return ResourceManager.GetString("scrollToAddCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Искать ссылку оригинальный размер изображения.
        /// </summary>
        public static string tryFindOriginalSizeCheckBox {
            get {
                return ResourceManager.GetString("tryFindOriginalSizeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество попыток повторной загрузки:.
        /// </summary>
        public static string twinLoadLabel {
            get {
                return ResourceManager.GetString("twinLoadLabel", resourceCulture);
            }
        }
    }
}
