//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatisticText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatisticText() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExHentaiDownloaderZ_5.Content.Locales.StatisticText", typeof(StatisticText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий шаг:.
        /// </summary>
        public static string CurrentStep {
            get {
                return ResourceManager.GetString("CurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус загрузки:.
        /// </summary>
        public static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Манга добавлена.
        /// </summary>
        public static string DownloadStatus_0 {
            get {
                return ResourceManager.GetString("DownloadStatus_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая ошибка загрузки.
        /// </summary>
        public static string DownloadStatus_1 {
            get {
                return ResourceManager.GetString("DownloadStatus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки информации.
        /// </summary>
        public static string DownloadStatus_2 {
            get {
                return ResourceManager.GetString("DownloadStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки страниц.
        /// </summary>
        public static string DownloadStatus_3 {
            get {
                return ResourceManager.GetString("DownloadStatus_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация загружена.
        /// </summary>
        public static string DownloadStatus_4 {
            get {
                return ResourceManager.GetString("DownloadStatus_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страницы загружены.
        /// </summary>
        public static string DownloadStatus_5 {
            get {
                return ResourceManager.GetString("DownloadStatus_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка количества страниц.
        /// </summary>
        public static string DownloadStatus_6 {
            get {
                return ResourceManager.GetString("DownloadStatus_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка страниц.
        /// </summary>
        public static string DownloadStatus_7 {
            get {
                return ResourceManager.GetString("DownloadStatus_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус загрузки:.
        /// </summary>
        public static string DownloadStatusCurrent {
            get {
                return ResourceManager.GetString("DownloadStatusCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбор ссылок.
        /// </summary>
        public static string DownloadStep_0 {
            get {
                return ResourceManager.GetString("DownloadStep_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка информации о манге.
        /// </summary>
        public static string DownloadStep_1 {
            get {
                return ResourceManager.GetString("DownloadStep_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка страниц манги.
        /// </summary>
        public static string DownloadStep_2 {
            get {
                return ResourceManager.GetString("DownloadStep_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка статусов загрузки.
        /// </summary>
        public static string DownloadStep_3 {
            get {
                return ResourceManager.GetString("DownloadStep_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дней.
        /// </summary>
        public static string TimeDays {
            get {
                return ResourceManager.GetString("TimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на часов.
        /// </summary>
        public static string TimeHours {
            get {
                return ResourceManager.GetString("TimeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бесконечно много времени.
        /// </summary>
        public static string TimeInfinity {
            get {
                return ResourceManager.GetString("TimeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осталось.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на меньше минуты.
        /// </summary>
        public static string TimeLessMinute {
            get {
                return ResourceManager.GetString("TimeLessMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на минут.
        /// </summary>
        public static string TimeMinutes {
            get {
                return ResourceManager.GetString("TimeMinutes", resourceCulture);
            }
        }
    }
}
