//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PopupMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PopupMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PopUpZ.Content.Locales.PopupMessages", typeof(PopupMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите сбросить настройки до значений по умолчанию? Внимание, выполнив данную операцию вы потеряете все установленные настройки!.
        /// </summary>
        public static string CanselSettingsQuestion {
            get {
                return ResourceManager.GetString("CanselSettingsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите очистить список загрузок? Внимание,это приведёт к полной потере текущего списка загрузок!.
        /// </summary>
        public static string ClearQuestion {
            get {
                return ResourceManager.GetString("ClearQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите прервать процесс загрузки и завершить работу программы?.
        /// </summary>
        public static string CloseQuestion {
            get {
                return ResourceManager.GetString("CloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка списка манги была успешно завершена!.
        /// </summary>
        public static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение списка загрузки было успешно завершено!.
        /// </summary>
        public static string loadComplete_0 {
            get {
                return ResourceManager.GetString("loadComplete_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка, во время чтения списка загрузки. Список не был прочитан корректно..
        /// </summary>
        public static string loadComplete_1 {
            get {
                return ResourceManager.GetString("loadComplete_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список загрузки не был проинициализирован. Пожалуйста перезапустите программу и попробуйте снова..
        /// </summary>
        public static string loadComplete_2 {
            get {
                return ResourceManager.GetString("loadComplete_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Во время сериализации списка загрузки произошла ошибка. Список не был прочитан корректно..
        /// </summary>
        public static string loadComplete_3 {
            get {
                return ResourceManager.GetString("loadComplete_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к записываемому файлу некорректен. Пожалуйста перепроверьте путь считывания и повторите попытку..
        /// </summary>
        public static string loadComplete_4 {
            get {
                return ResourceManager.GetString("loadComplete_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка формирования сообщения об ошибке =)..
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не было выбрано ни одной строки для удаления!.
        /// </summary>
        public static string RemoveError {
            get {
                return ResourceManager.GetString("RemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись списка загрузки была успешно завершена!.
        /// </summary>
        public static string saveComplete_0 {
            get {
                return ResourceManager.GetString("saveComplete_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка, во время записи списка загрузки. Список не был записан корректно..
        /// </summary>
        public static string saveComplete_1 {
            get {
                return ResourceManager.GetString("saveComplete_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка, во время сериализации списка загрузки. Список не был записан корректно..
        /// </summary>
        public static string saveComplete_2 {
            get {
                return ResourceManager.GetString("saveComplete_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список загрузки не был проинициализирован. Пожалуйста перезапустите программу и попробуйте снова..
        /// </summary>
        public static string saveComplete_3 {
            get {
                return ResourceManager.GetString("saveComplete_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь для записи некорректен. Пожалуйста перепроверьте путь записи и повторите попытку..
        /// </summary>
        public static string saveComplete_4 {
            get {
                return ResourceManager.GetString("saveComplete_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки были успешно применены!.
        /// </summary>
        public static string SaveSettings_0 {
            get {
                return ResourceManager.GetString("SaveSettings_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка, во время применения настроек. Пожалуйста перезапустите программу, и попробуйте ещё раз..
        /// </summary>
        public static string SaveSettings_1 {
            get {
                return ResourceManager.GetString("SaveSettings_1", resourceCulture);
            }
        }
    }
}
